const searchCities = [
    "Dhaka", "Biman_Bandar", "Ibrahimabad", "Chatmohar", "Natore", "Santahar",
    "Talora", "Bogura", "Sonatola", "Bonar_Para", "Gaibandha", "Bamondanga",
    "Pirgacha", "Kaunia", "Kurigram", "Rangpur", "Joypurhat", "Parbatipur",
    "Dinajpur", "Pirganj", "Thakurgaon_Road", "Panchagarh", "Joydebpur", "Tangail",
    "SH M Monsur Ali", "Ullapara", "Ishwardi Bypass", "Akkelpur", "Panchbibi",
    "Birampur", "Fulbari", "Chirirbandar", "Setabganj", "Ruhia", "Kismat", "Khulna",
    "Noapara", "Jashore", "Mubarakganj", "Kotchandpur", "Darshana_Halt", "Chuadanga",
    "Alamdanga", "Poradaha", "Bheramara", "Paksey", "Ishwardi", "Ahsanganj", "Saidpur",
    "Nilphamari", "Domar", "Chilahati", "Jamtail", "Boral_Bridge", "Abdulpur", "Arani",
    "Rajshahi", "Daulatpur", "Gobra", "Borashi", "Gopalganj", "Chandradighalia",
    "Choto Bahirbag", "Chapta", "Kashiani", "Boalmari_Bazar", "Madhukhali", "Baharpur",
    "Kalukhali", "Pangsha", "Khoksha", "Kumarkhali", "Kushtia_Court", "Sardah_Road",
    "Mirzapur", "Sirajganj_Bazar", "Sirajganjraipur", "SOYDABAD", "Hi-Tech City",
    "Azim Nagar", "Teesta_Junction", "Lalmonirhat", "Madhnagar", "Badarganj", "Mawa",
    "Padma", "Shibchar", "Bhanga", "Pukuria", "Talma", "Faridpur", "Amirabad",
    "Pachuria", "Rajbari", "Mirpur", "Muladhuli", "Safdarpur", "Shibganj", "Benapole",
    "Jhikargacha", "Jamalganj", "Hili", "Dhalarchar", "Badherhat", "Kashinathpur",
    "Sathia_Rajapur", "Tantibandha", "Dublia", "Raghabpur", "Pabna", "Tebunia",
    "Dashuria", "Majhgram", "Sitlai", "Kakonhat", "Lolitnagar", "Amnura_Bypass",
    "Chapainawabganj", "Mahimaganj", "Aditmari", "Kankina", "Tushbhandar", "Hatibandha",
    "Barkhata", "Patgram", "Burimari", "Bhomradah", "Kholahati", "Badiakhali",
    "Chattogram", "Feni", "Gunabati", "Laksam", "Cumilla", "Akhaura", "Brahmanbaria",
    "Bhairab_Bazar", "Gafargaon", "Mymensingh", "Piyarpur", "Jamalpur_Town",
    "Melandah_Bazar", "Islampur_Bazar", "Dewanganj_Bazar", "Noakhali", "Maijdi Court",
    "Choumuhani", "Bajra", "Sonaimuri", "Natherpetua", "Quasba", "Ashuganj",
    "Narsingdi", "Azampur", "Nayapara", "Shaistaganj", "Sreemangal", "Bhanugach",
    "Kulaura", "Maijgaon", "Sylhet", "Mukundapur", "Harashpur", "Montola",
    "Shahaji_Bazar", "Nangolkot", "Shamshernagar", "Baramchal", "Kumira", "Narundi",
    "Kendua_Bazar", "Sarishabari", "Tarakandi", "Kuliarchar", "Bajitpur", "Sararchar",
    "Manikkhali", "Gachihata", "Kishorganj", "Nandina", "Sreepur", "Kaoraid",
    "Methikanda", "Bhatiary", "Atharabari", "Gouripur_Myn", "Shyamgonj", "Netrakona",
    "Thakrokona", "Barhatta", "Mohanganj", "Bidyaganj", "Jaforshahi",
    "Jagannathgonj_Bazar", "Hemnagar", "Bhuapur", "Hasanpur", "Shashidal",
    "Chitoshi_Road", "Meher", "Hajiganj", "Modhu_Road", "Chandpur_Court", "Chandpur",
    "Lokmanpur", "Rajshahi_Court", "Amnura", "Nachole", "Rohanpur", "Mahendranagar",
    "Mirbagh", "Shyampur", "Birol", "Bhotmari", "Baura", "Cox's Bazar",
    "Manmathapur", "Kawgaon", "Kanchan_Junction", "Mongalpur", "Sultanpur",
    "Akhanagar", "Nayaniburuj", "Singia", "Narail", "Lohagora", "Bhanga_Junction",
    "Sholoshohor", "Janali_Hat", "Patiya", "Dohazari", "Satkania", "Chakaria",
    "Dulahazara", "Ramu", "ISLAMABAD", "HARBANG", "LOHAGARA", "GOMDANDI"
];

export const citiesOptions = searchCities.map(city => ({
    value: city,
    label: city
}));